[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/logo-burgas-sliven.png"
  [headers.values]
    Cache-Control = "max-age=300"

[[headers]]
  for = "/share-1200x630.png"
  [headers.values]
    Cache-Control = "max-age=300"

[[headers]]
  for = "/share-1200x1200.png"
  [headers.values]
    Cache-Control = "max-age=86400"